---
仅将cellranger输出结果用R读入，并进行SoupX处理
已经完成的部分不再重读检测
另外，虽然sc-best-practices首先进行基于MAD的outlier处理，我们优先进行基于R的读取的SoupX处理
---

```{r}
library(cowplot)
library(Seurat)
library(SoupX)
library(Matrix)
library(dplyr)
library(ggplot2)
library("irlba")
packageVersion("irlba")

options(repos = c(USTC="https://mirrors.ustc.edu.cn/CRAN/"))
setwd(dir = '/data/HeLab/bio/IBD_plus/01_SeuratReadIn')
```

```{r}
IgGenes <- c('IGHA1','IGHA2','IGHG1','IGHG2','IGHG3','IGHG4',
             'IGHM','IGLC1','IGLC2','IGLC3','IGLC4','IGLC5','IGLC6','IGLC7',
             'IGKC','IGKV1-5','IGKV3-20','IGLV1-40','IGLV1-47','IGLV2-11','IGLV2-14','IGLV2-23','IGLV6-57',
             'JCHAIN')
# HbGenes <- c('HBB','HBA1','HBA2')
RiboGenes <- c('RPL22', 'RPL11', 'RPS6KA1', 'RPS8', 'RPL5', 'RPS27', 'RPS6KC1', 'RPS7', 'RPS27A', 'RPL31', 'RPL37A', 'RPL32', 'RPL15', 'RPSA', 'RPL14', 'RPL29', 'RPL24', 'RPL22L1', 'RPL39L', 'RPL35A', 'RPL9', 'RPL34-AS1', 'RPL34', 'RPS3A', 'RPL37', 'RPS23', 'RPS14', 'RPL26L1', 'RPS18', 'RPS10-NUDT3', 'RPS10', 'RPL10A', 'RPL7L1', 'RPS12', 'RPS6KA2', 'RPS20', 'RPL7', 'RPL30', 'RPL8', 'RPS6', 'RPL35', 'RPL12', 'RPL7A', 'RPS24', 'RPLP2', 'RPL27A', 'RPS13', 'RPS6KA4', 'RPS6KB2', 'RPS6KB2-AS1', 'RPS3', 'RPS25', 'RPS26', 'RPL41', 'RPL6', 'RPLP0', 'RPL21', 'RPL10L', 'RPS29', 'RPL36AL', 'RPS6KL1', 'RPS6KA5', 'RPS27L', 'RPL4', 'RPLP1', 'RPS17', 'RPL3L', 'RPS2', 'RPS15A', 'RPL13', 'RPL26', 'RPL23A', 'RPL23', 'RPL19', 'RPL27', 'RPS6KB1', 'RPL38', 'RPL17', 'RPS15', 'RPL36', 'RPS28', 'RPL18A', 'RPS16', 'RPS19', 'RPL18', 'RPL13A', 'RPS11', 'RPS9', 'RPL28', 'RPS5', 'RPS21', 'RPL3', 'RPS19BP1', 'RPS6KA3', 'RPS4X', 'RPS6KA6', 'RPL36A', 'RPL39', 'RPL10', 'RPS4Y1', 'RPS4Y2')
# MTGenes <- c('MT-ND1', 'MT-ND2', 'MT-CO1', 'MT-CO2', 'MT-ATP8', 'MT-ATP6', 'MT-CO3','MT-ND3', 'MT-ND4L', 'MT-ND4', 'MT-ND5', 'MT-ND6', 'MT-CYB','MTRNR2L12')
Manual <- c("MALAT1")
Pollutions <- list(Ig=IgGenes,Rb=RiboGenes)
```


```{r}
inputdir <- "/data/HeLab/bio/IBD_plus/single_cell_data/GSE189754/cellranger_output"
GenesetID <- "GSE189754"
scData_Raw <- RunSoupX(input_dir=inputdir,
                       sample_names=list.files(inputdir))
save(scData_Raw,file = paste0("01_SeuratReadIn(SoupX)_",GenesetID,".Rdata"))
#############
inputdir <- "/data/HeLab/bio/IBD_plus/single_cell_data/GSE116222/cellranger_output"
GenesetID <- "GSE116222"
scData_Raw <- RunSoupX(input_dir=inputdir,
                       sample_names=list.files(inputdir),
                       pollution_list=Pollutions)
save(scData_Raw,file = paste0("01_SeuratReadIn(SoupX)_",GenesetID,".Rdata"))
#############
inputdir <- "/data/HeLab/bio/IBD_plus/single_cell_data/XY/cellranger_output"
GenesetID <- "XY"
scData_Raw <- RunSoupX(input_dir=inputdir,
                       sample_names=list.files(inputdir))
check_seurat_assay_slots_simple(scData_Raw[[1]])
save(scData_Raw,file = paste0("01_SeuratReadIn(SoupX)_",GenesetID,".Rdata"))


```

```{r}


inputdir <- "/data/HeLab/bio/IBD_plus/single_cell_data/GSE157477/filtered_output"
GenesetID <- "GSE157477"
scData_Raw <- ReadIn10X(Input=inputdir,suffix="filtered_gene_bc_matrices")
gc()
save(scData_Raw,file = paste0("01_SeuratReadIn(ReadIn)_",GenesetID,".Rdata"))

inputdir <- "/data/HeLab/bio/IBD_plus/single_cell_data/GSE198616/filtered_output"
GenesetID <- "GSE198616"
scData_Raw <- ReadIn10X(Input=inputdir,suffix="filtered_gene_bc_matrices")
gc()
save(scData_Raw,file = paste0("01_SeuratReadIn(ReadIn)_",GenesetID,".Rdata"))
```
处理一下HRA
```{r}
input_dir <- "/data/HeLab/bio/IBD_plus/01_SeuratReadIn/Rdata"
file_list <- list.files(input_dir)
scData_Raw <- list()
for (i in seq_along(file_list)){
  load(file.path(input_dir, file_list[i]))
  scData_Raw[[i]] <- sce
  rm(sce);gc()
}
save(scData_Raw,file = paste0("01_SeuratReadIn(SoupX)_","HRA000072",".Rdata"))

```


进行信息更新
```{r}
library(openxlsx)

meta_table <- read.xlsx("/data/HeLab/bio/IBD_analysis/assets/Sample_Grouping.xlsx")
meta_clean <- meta_table %>%
  select(-SRA_selector, -`tissue-origin`) %>%    # 去掉不需要的列
  distinct(orig.ident, .keep_all = TRUE)         # 保证 orig.ident 唯一
# 假设你的原始 meta_table 已经读入 R，列名中包含 `tissue-origin`，此处改为合法 R 名称 tissue.origin


##############################################
GenesetID <- "GSE198616"
load(paste0("/data/HeLab/bio/IBD_plus/01_SeuratReadIn/01_SeuratReadIn(ReadIn)_",GenesetID,".Rdata"))
head(scData_Raw[[1]]@meta.data)
scData_Raw <- updateSeuratMeta(scData_Raw, meta_clean, col.by="orig.ident");gc()
head(scData_Raw[[1]]@meta.data)
save(scData_Raw,file = paste0("01_SeuratReadIn(ReadIn)_",GenesetID,".Rdata"))
##############################################
file2process <- c(
        "01_SeuratReadIn(ReadIn)_GSE157477.Rdata", "01_SeuratReadIn(SoupX)_GSE116222.Rdata",
        "01_SeuratReadIn(SoupX)_HRA000072.Rdata",
                   "01_SeuratReadIn(SoupX)_GSE225199.Rdata","01_SeuratReadIn(SoupX)_XY.Rdata"
        )
base_dir <- "/data/HeLab/bio/IBD_plus/01_SeuratReadIn"

for (filename in file2process){
  message("Processing: ", filename)
  load(file.path(base_dir, filename))
  message("Before: ", paste0(capture.output(head(scData_Raw[[1]]@meta.data)), collapse = "\n"))
  scData_Raw <- updateSeuratMeta(scData_Raw, meta_clean, col.by="orig.ident")
  message("After:  ", paste0(capture.output(head(scData_Raw[[1]]@meta.data)), collapse = "\n"))
  save(scData_Raw,file = file.path(base_dir, filename))
  rm(scData_Raw);gc()
}

# 这个格式因为有SRR所以怪怪的，手动做一下
filename <- "01_SeuratReadIn(SoupX)_GSE189754.Rdata"
load(file.path(base_dir, filename))
head(scData_Raw[[1]]@meta.data)
library(tidyr)

meta_sra <- meta_table %>%
  select(-`tissue-origin`) %>%    # 去掉不需要的列
  separate_rows(SRA_selector, sep = ",")
meta_sra <- meta_sra[meta_sra$SRA_selector != "ignored",]

c
scData_Raw <- updateSeuratMeta(scData_Raw, meta_sra, col.by="SRA_selector")
save(scData_Raw,file = file.path(base_dir, filename))


```
