 1. QC
2. 简单降维聚类
3. Doublet检测
 因此这一步主要是quality control，我们随后在python中利用scvi进行批次间整合

```{r}
library(SeuratObject)
  # 目前Doubletfinder没有做版本管理，刚需v5版本的SeuratObject
library(Seurat)
library(Matrix)
library(dplyr)
library(ggplot2)
library(DoubletFinder)
library(RSpectra)
library(matrixStats)
library(Rfast)

  # 可能需要检查RSpectra，或检查irlba版本以免Doubletfinder调用UMAP过程产生问题
options(repos = c(USTC="https://mirrors.ustc.edu.cn/CRAN/"))
setwd(dir = '/data/HeLab/bio/IBD_plus/01_SeuratReadIn')
```


第一步：基础质量控制

用01_SeuratReadIn(ReadIn)_GSE157477.Rdata做一个检测
```{r}
# filename = "01_SeuratReadIn(ReadIn)_GSE157477.Rdata"
# filename = "01_SeuratReadIn(SoupX)_HRA000072.Rdata"
# filename = "01_SeuratReadIn(SoupX)_GSE116222.Rdata"
# filename = "01_SeuratReadIn(SoupX)_GSE225199.Rdata"
# filename = "01_SeuratReadIn(ReadIn)_GSE198616.Rdata"
filename = "01_SeuratReadIn(SoupX)_XY.Rdata"
load(filename)
check_seurat_assay_slots_simple(scData_Raw[[1]])
## 肉眼检查
counts_matrix <- GetAssayData(scData_Raw[[12]], assay = "RNA", slot = "counts")
head(summary(counts_matrix),n=100)

## 手动对HRA000072进行一次处理
# for(i in seq_along(scData_Raw)){
#   counts_matrix <- GetAssayData(scData_Raw[[i]], assay = "RNA", slot = "counts")
#   rounded_counts <- round(counts_matrix)
#   scData_Raw[[i]] <- SetAssayData(scData_Raw[[i]], assay = "RNA", slot = "counts", new.data = rounded_counts)
# }




scData_QC <- Score_organelle(scData_Raw)
scData_QC <- Compute_QC_metrics(scData_QC)
gc()
scData_clean <- Remove_Outlier(scData_QC, nmads = 3, mt_nmads = 5, mt_thresh = 10)
for (i in seq_along(scData_clean)) {
  scData_clean[[i]] <- RunDimReduc(scData_clean[[i]])
}
check_seurat_assay_slots_simple(scData_clean[[1]])

# save(scData_clean,file="/data/HeLab/bio/IBD_analysis/tmp/GSE157477_tmp.Rdata")
# load("/data/HeLab/bio/IBD_analysis/tmp/GSE157477_tmp.Rdata")
scData_clean <- RunDoubletFinder(scData_clean)
head(scData_clean[[1]]@meta.data)
table(scData_clean[[1]]@meta.data$DF_hi_lo)
table(scData_clean[[11]]@meta.data$DF_hi_lo)

new_fn <- paste0("/data/HeLab/bio/IBD_analysis/output/Step02_QC/",gsub(pattern = "01_SeuratReadIn",
                                                                         replacement = "02_DF",x = filename))
check_seurat_assay_slots_simple(scData_clean[[1]])

save(scData_clean,file=new_fn)
```

批量循环
```{r}
file_list <- c(
        # "01_SeuratReadIn(ReadIn)_GSE198616.Rdata",
        #        "01_SeuratReadIn(SoupX)_GSE116222.Rdata",
        # "01_SeuratReadIn(SoupX)_GSE189754.Rdata",
        #        "01_SeuratReadIn(SoupX)_GSE225199.Rdata",
               "01_SeuratReadIn(SoupX)_HRA000072.Rdata"#,
        #        "01_SeuratReadIn(SoupX)_XY.Rdata"
        )

fn = "01_SeuratReadIn(SoupX)_GSE189754.Rdata"
for (fn in file_list){
  load(fn)
  scData_QC <- Score_organelle(scData_Raw)
  scData_QC <- Compute_QC_metrics(scData_QC,method = "Rfast")
  scData_clean <- Remove_Outlier(scData_QC, nmads = 3, mt_nmads = 5, mt_thresh = 10)
  gc()
  for (i in seq_along(scData_clean)) {
    scData_clean[[i]] <- RunDimReduc(scData_clean[[i]])
  }
  is.null(scData_clean[[1]]@meta.data$seurat_clusters)
  scData_clean <- RunDoubletFinder(scData_clean)
  table(scData_clean[[1]]@meta.data$)
  new_fn <- paste0("/data/HeLab/bio/IBD_analysis/output/Step02_QC/",gsub(pattern = "01_SeuratReadIn",
                                                                         replacement = "02_DF",x = fn))
  save(scData_clean,file=new_fn)
  rm(scData_QC,scData_clean,scData_Raw);gc()
}


# load("/data/HeLab/bio/IBD_analysis/output/Step02_QC")
```


new_fn <- paste0("/data/HeLab/bio/IBD_analysis/output/Step02_QC/",gsub(pattern = "01_SeuratReadIn",
                                                                         replacement = "02_DF",x = fn))
save(scData_clean,file=new_fn)
gc()
ls()